on:
  push:
    branches:
      - master
  pull_request:

name: Linting

jobs:
  lint:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install prettier
        run: |
          yarn global add prettier
      - name: Install black
        run: |
          pip install git+https://github.com/psf/black
      - name: Install cairo-lang
        run: |
          pip install cairo-lang
      - name: Check Python format
        run: |
          black --check "./tests"
      - name: Check Yaml format
        run: |
          prettier --check "**/*.{yaml,yml}"
      - name: Check Cairo format
        run: |
          cairo-format -c ./src/zklend/*.cairo
